"""The anti-drift test.

`mira_agent.core` and the Mira control plane must produce byte-identical results, or
signatures verify against bytes nobody stored and the whole chain is
decorative. These vectors were generated by the SERVER's implementation; this
suite asserts the client reproduces them exactly.

If one of these fails, do not "fix the test" — one of the two implementations
has moved, and every record signed by the newer one is unverifiable by the
older.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

from mira_agent_core import (
    PAYLOAD_TYPE,
    SigningKey,
    canonical,
    content_hash,
    hash_leaf,
    key_id,
    pae,
    sha256_hex,
    verify_signature,
)
from mira_agent_core.mmr import InclusionProof, verify_inclusion, verify_root
from mira_agent.policy import PolicyBundle

VECTORS = json.loads(
    (Path(__file__).parent.parent / "vectors" / "conformance.json").read_text()
)


def case(name: str) -> dict:
    return next(c for c in VECTORS["cases"] if c["name"] == name)


def test_statement_canonicalises_to_the_same_bytes():
    c = case("statement_canonicalisation")
    produced = canonical(c["statement"])
    assert produced == base64.b64decode(c["canonical_b64"]), (
        "client canonicalisation diverged from the control plane"
    )


def test_record_hash_matches():
    c = case("statement_canonicalisation")
    assert sha256_hex(canonical(c["statement"])) == c["record_hash"]


def test_dsse_pae_matches():
    c = case("statement_canonicalisation")
    payload = canonical(c["statement"])
    assert sha256_hex(pae(PAYLOAD_TYPE, payload)) == c["pae_sha256"]


def test_key_id_and_signature_match():
    """Ed25519 is deterministic, so the same seed over the same bytes must
    produce the same signature on both sides."""
    sig_case = case("signature")
    stmt_case = case("statement_canonicalisation")

    k = SigningKey.from_seed(sig_case["key_name"], bytes.fromhex(sig_case["seed_hex"]))
    assert k.key_id == sig_case["key_id"]
    assert k.public_b64 == sig_case["public_b64"]
    assert key_id(sig_case["key_name"], k.public_bytes) == sig_case["key_id"]

    payload = canonical(stmt_case["statement"])
    produced = base64.b64encode(k.sign(pae(PAYLOAD_TYPE, payload))).decode()
    assert produced == sig_case["signature_b64"]

    # and the server's signature verifies under the client's verifier
    assert verify_signature(
        base64.b64decode(sig_case["public_b64"]),
        base64.b64decode(sig_case["signature_b64"]),
        pae(PAYLOAD_TYPE, payload),
    )


@pytest.mark.parametrize("sample", case("content_hash")["samples"])
def test_content_hash_matches(sample):
    assert content_hash(sample["value"]) == sample["hash"]


def test_mmr_leaf_hashing_and_root_match():
    c = case("mmr")
    leaves = [base64.b64decode(x) for x in c["leaves_b64"]]
    assert hash_leaf(leaves[3]).hex() == c["leaf3_hash_hex"]


def test_mmr_inclusion_proof_verifies_against_the_server_root():
    c = case("mmr")
    leaves = [base64.b64decode(x) for x in c["leaves_b64"]]
    proof = InclusionProof.from_dict(c["proof"])
    assert verify_inclusion(leaves[3], 3, proof)
    assert verify_root(proof, c["root_hex"])


def test_a_tampered_leaf_fails_inclusion():
    c = case("mmr")
    proof = InclusionProof.from_dict(c["proof"])
    assert not verify_inclusion(b"leaf-3-tampered", 3, proof)


def test_policy_bundle_digest_matches():
    """The client pins this digest and every decision records it, so the two
    sides must agree on how a bundle canonicalises."""
    c = case("policy_bundle")
    bundle = PolicyBundle.from_dict(c["bundle"])
    assert bundle.digest == c["digest"]


# ---------------------------------------------------------- both backends
# The Rust core exists so a Go or Rust gateway can link one implementation
# instead of maintaining a third. These run the SAME server-generated vectors
# against it, which is the only proof that means anything.

rust = pytest.importorskip(
    "mira_agent_core_rs", reason="Rust core not built; see core-rs/README.md"
)


def test_rust_canonicalises_to_the_server_bytes():
    c = case("statement_canonicalisation")
    assert rust.canonicalize(json.dumps(c["statement"])) == base64.b64decode(
        c["canonical_b64"]
    )


def test_rust_record_hash_matches():
    c = case("statement_canonicalisation")
    assert rust.record_hash(json.dumps(c["statement"])) == c["record_hash"]


def test_rust_dsse_pae_matches():
    c = case("statement_canonicalisation")
    payload = canonical(c["statement"])
    assert rust.pae(PAYLOAD_TYPE, payload) == pae(PAYLOAD_TYPE, payload)


def test_rust_signature_is_identical():
    sig_case, stmt_case = case("signature"), case("statement_canonicalisation")
    seed = bytes.fromhex(sig_case["seed_hex"])
    payload = canonical(stmt_case["statement"])
    assert base64.b64encode(rust.public_from_seed(seed)).decode() == sig_case["public_b64"]
    assert base64.b64encode(
        rust.sign(seed, pae(PAYLOAD_TYPE, payload))
    ).decode() == sig_case["signature_b64"]


@pytest.mark.parametrize("sample", case("content_hash")["samples"])
def test_rust_content_hash_matches(sample):
    """The case that caught real divergence: an integer past 2^53 must be
    carried as a string by BOTH implementations, or a record signed by one
    fails verification by the other."""
    assert "sha256:" + rust.record_hash(json.dumps(sample["value"])) == sample["hash"]


def test_rust_verifies_the_server_mmr_proof():
    c = case("mmr")
    leaves = [base64.b64decode(x) for x in c["leaves_b64"]]
    p = c["proof"]
    assert rust.hash_leaf(leaves[3]).hex() == c["leaf3_hash_hex"]
    assert rust.verify_inclusion(leaves[3], 3, p["leaf_pos"], p["path"], p["peaks"])
    assert rust.verify_root(p["peaks"], p["mmr_size"], c["root_hex"])


def test_rust_rejects_a_tampered_leaf():
    c = case("mmr")
    p = c["proof"]
    assert not rust.verify_inclusion(b"tampered", 3, p["leaf_pos"], p["path"], p["peaks"])
