"""MSEP anti-drift vectors.

`vectors/msep.json` was generated by the control plane's `mira.msep`. The SDK's
port must reproduce every byte: the state digest, the envelope's signing bytes
and commitment, the adverse assertion, the certificate, the Security Event
Token's signing input, and the receipt. A signature made by one side has to
verify on the other, or an envelope minted by a Mira boundary is decorative to
an SDK boundary and vice versa.

If one of these fails, do not fix the test. One of the two implementations
moved.
"""
import json
from pathlib import Path

import pytest

from _msep_keys import SigningKey
from mira_agent.msep import Envelope, ExecutionState, Permissions, fast
from mira_agent.msep.envelope import Capability
from mira_agent.msep.receipt import Receipt
from mira_agent.msep.signals import ingest
from mira_agent.msep.trust import AdverseTrustAssertion
from mira_agent.msep.trust_root import BoundaryCertificate, CertificateStore, TrustAnchor
from mira_agent.msep.verify import KeyCache, verify_inbound
from mira_agent.msep.trust import TrustEpoch

V = json.loads((Path(__file__).parent.parent / "vectors" / "msep.json").read_text())


def _key(which):
    k = V["keys"][which]
    return SigningKey.from_seed(k["name"], bytes.fromhex(k["seed_hex"]))


def test_keys_derive_identically():
    for which in ("boundary", "root"):
        k = _key(which)
        assert k.public_bytes.hex() == V["keys"][which]["public_hex"]
        assert k.key_id == V["keys"][which]["key_id"]


def test_state_digest_matches():
    j = V["state"]["jcs"]
    st = ExecutionState(j["payloadDigest"], j["action"], j["target"], j["artifact"],
                        context_digest=j["contextDigest"],
                        permissions=Permissions.from_jcs(j["permissions"]),
                        side_effects=j["sideEffects"])
    assert st.to_jcs() == j
    assert st.digest() == V["state"]["digest"]


def test_envelope_bytes_commitment_and_signature_match():
    e = Envelope.from_wire(V["envelope"]["wire"])
    assert e.to_wire() == V["envelope"]["wire"]
    assert e.signing_bytes().hex() == V["envelope"]["signing_bytes_hex"]
    assert e.commitment() == V["envelope"]["commitment"]
    assert e.wire_size() == V["envelope"]["wire_size"]
    # the control plane's signature verifies here ...
    assert e.signature_valid(_key("boundary").public_bytes)
    # ... and signing here reproduces it exactly (Ed25519 is deterministic)
    assert e.sign(_key("boundary")).signature == e.signature


def test_a_control_plane_envelope_verifies_at_an_sdk_boundary():
    e = Envelope.from_wire(V["envelope"]["wire"])
    j = V["state"]["jcs"]
    st = ExecutionState(j["payloadDigest"], j["action"], j["target"], j["artifact"],
                        context_digest=j["contextDigest"],
                        permissions=Permissions.from_jcs(j["permissions"]),
                        side_effects=j["sideEffects"])
    keys = KeyCache({e.key_id: _key("boundary").public_bytes})
    v = verify_inbound(e, keys=keys, epoch=TrustEpoch(3), destination="node-b", state=st,
                       policy_digest="sha256:policy-vector", now_ms=e.issued_ms + 1)
    assert v.ok, v.reasons


def test_adverse_assertion_matches():
    c = AdverseTrustAssertion.from_wire(V["adverse"]["wire"])
    assert c.to_wire() == V["adverse"]["wire"]
    assert c.signing_bytes().hex() == V["adverse"]["signing_bytes_hex"]
    assert c.commitment() == V["adverse"]["commitment"]
    assert c.signature_valid(_key("boundary").public_bytes)


def test_certificate_matches_and_installs():
    cert = BoundaryCertificate.from_wire(V["certificate"]["wire"])
    assert cert.signing_bytes().hex() == V["certificate"]["signing_bytes_hex"]
    store = CertificateStore([TrustAnchor("acme-root", _key("root").public_bytes)],
                             now_ms=lambda: cert.not_before_ms + 1)
    store.install(cert)                       # verifies against the root
    assert store.resolve(cert.key_id, attestation="tpm:pcr7=vector")


def test_security_event_token_ingests():
    keys = KeyCache({V["keys"]["boundary"]["key_id"]: _key("boundary").public_bytes,
                     V["keys"]["root"]["key_id"]: _key("root").public_bytes})
    card = ingest(V["set"]["compact"], resolve_key=keys.get, expected_audience="node-c",
                  now_ms=1_800_000_000_000)
    assert card.reason == "honey_tool_trip"
    assert V["set"]["compact"].startswith(V["set"]["signing_input"])


def test_receipt_serialises_identically():
    r = V["receipt"]["jcs"]
    rec = Receipt(inbound_commitment=r["inboundCommitment"], successor_commitment=None,
                  identity=r["identity"], boundary=r["boundary"], disposition=r["disposition"],
                  action_released=r["actionReleased"], policy_digest=r["policyDigest"],
                  epoch=r["epoch"], state_digest=r["stateDigest"], at_ms=r["atMs"],
                  reasons=r["reasons"], parent_commitments=r["parentCommitments"],
                  signer_key_id=r["signerKeyId"])
    assert rec.to_jcs() == r


def test_mac_tag_matches_the_control_plane():
    if not fast.AVAILABLE:
        pytest.skip("MAC mode needs the Rust core")
    e = Envelope.from_wire(V["envelope"]["wire"])
    key = bytes.fromhex(V["mac"]["key_hex"])
    assert fast.mac_tag(key, e.signing_body()) == V["mac"]["tag"]
    assert fast.mac_verify(key, e.signing_body(), V["mac"]["tag"])
