//! The Mira record core, in Rust.
//!
//! This exists for one reason: there must be exactly ONE implementation of
//! canonicalisation, hashing and signing, or signatures verify against bytes
//! nobody stored. Python has one. A Go or Rust gateway would need a second.
//! Rather than maintain two and hope they agree, this crate is the
//! implementation, and Python calls into it.
//!
//! It is verified the only way that means anything: against
//! `vectors/conformance.json`, the same fixtures generated by the control
//! plane that the pure-Python core is already pinned to. One vector file,
//! every implementation, byte for byte.
//!
//! JCS number formatting is where hand-rolled canonicalisers go wrong, so
//! `serde_jcs` does that job rather than a bespoke serialiser here.

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};

pub const PAYLOAD_TYPE: &str = "application/vnd.mira.provenance+json";
const LEAF_PREFIX: u8 = 0x00;
const NODE_PREFIX: u8 = 0x01;

// ---------------------------------------------------------------- canonical

/// Coerce a value into something JCS can round-trip safely.
///
/// This is part of Mira's RECORD FORMAT, not an artefact of any one language,
/// which is why it lives here rather than in a binding. JCS serialises numbers
/// per ECMAScript, so an integer at or beyond 2^53 cannot survive a round trip
/// through a double — it is carried as a string instead. Non-finite floats get
/// the same treatment.
///
/// The conformance vectors caught this the first time the Rust side skipped
/// it: every case passed except an integer past 2^53, where two implementations
/// canonicalised the same record differently and every signature over it would
/// have verified on one side and failed on the other.
fn jcs_safe(value: serde_json::Value) -> serde_json::Value {
    use serde_json::Value;
    const MAX_SAFE: i128 = 1i128 << 53;
    match value {
        Value::Object(map) => Value::Object(
            map.into_iter().map(|(k, v)| (k, jcs_safe(v))).collect(),
        ),
        Value::Array(items) => Value::Array(items.into_iter().map(jcs_safe).collect()),
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                if (i as i128).abs() >= MAX_SAFE {
                    return Value::String(i.to_string());
                }
            } else if let Some(u) = n.as_u64() {
                if (u as i128) >= MAX_SAFE {
                    return Value::String(u.to_string());
                }
            } else if let Some(f) = n.as_f64() {
                if !f.is_finite() {
                    return Value::String(f.to_string());
                }
            }
            Value::Number(n)
        }
        other => other,
    }
}

/// RFC 8785 canonical bytes for a JSON document supplied as text.
///
/// Text in, bytes out: crossing the FFI boundary with an already-serialised
/// document avoids converting Python objects to serde values, which is both
/// slower and a second place for representation to drift.
pub fn canonicalize(json_text: &str) -> Result<Vec<u8>, String> {
    let value: serde_json::Value =
        serde_json::from_str(json_text).map_err(|e| format!("not valid JSON: {e}"))?;
    serde_jcs::to_vec(&jcs_safe(value)).map_err(|e| format!("could not canonicalise: {e}"))
}

pub fn sha256_hex(data: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(data);
    format!("{:x}", h.finalize())
}

/// DSSE Pre-Authentication Encoding — what is actually signed.
pub fn pae(payload_type: &str, payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len() + payload_type.len() + 32);
    out.extend_from_slice(b"DSSEv1 ");
    out.extend_from_slice(payload_type.len().to_string().as_bytes());
    out.push(b' ');
    out.extend_from_slice(payload_type.as_bytes());
    out.push(b' ');
    out.extend_from_slice(payload.len().to_string().as_bytes());
    out.push(b' ');
    out.extend_from_slice(payload);
    out
}

// --------------------------------------------------------------------- MMR

pub fn hash_leaf(payload: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update([LEAF_PREFIX]);
    h.update(payload);
    h.finalize().into()
}

fn hash_pos_pair(pos: u64, left: &[u8], right: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update([NODE_PREFIX]);
    h.update(pos.to_be_bytes());
    h.update(left);
    h.update(right);
    h.finalize().into()
}

fn all_ones(pos: u64) -> bool {
    pos != 0 && ((1u128 << (64 - pos.leading_zeros())) - 1) as u64 == pos
}

fn most_sig_bit(pos: u64) -> u64 {
    1u64 << (63 - pos.leading_zeros())
}

pub fn index_height(i: u64) -> u32 {
    let mut pos = i + 1;
    while !all_ones(pos) {
        pos -= most_sig_bit(pos) - 1;
    }
    64 - pos.leading_zeros() - 1
}

pub fn leaf_index_to_pos(mut leaf_index: u64) -> u64 {
    let mut total = 0u64;
    while leaf_index > 0 {
        let h = 64 - leaf_index.leading_zeros();
        total += (1u64 << h) - 1;
        leaf_index -= 1u64 << (h - 1);
    }
    total
}

/// Recompute leaf -> peak and check the result is one of the proof's peaks.
///
/// On its own this proves nothing about the log; the peaks must still fold to
/// a root somebody signed. Always pair with `verify_root`.
pub fn verify_inclusion(payload: &[u8], leaf_index: u64, leaf_pos: u64,
                        path: &[String], peaks: &[String]) -> bool {
    if leaf_index_to_pos(leaf_index) != leaf_pos {
        return false;
    }
    let mut pos = leaf_pos;
    let mut node = hash_leaf(payload);
    let mut height: u32 = 0;
    for sibling_hex in path {
        let sibling = match hex_to_bytes(sibling_hex) {
            Some(b) => b,
            None => return false,
        };
        if index_height(pos + 1) > height {
            pos += 1;
            node = hash_pos_pair(pos, &sibling, &node);
        } else {
            pos += 2u64 << height;
            node = hash_pos_pair(pos, &node, &sibling);
        }
        height += 1;
    }
    let got = bytes_to_hex(&node);
    peaks.iter().any(|p| *p == got)
}

pub fn verify_root(peaks: &[String], mmr_size: u64, expected_root_hex: &str) -> bool {
    if peaks.is_empty() {
        return false;
    }
    let decoded: Option<Vec<Vec<u8>>> = peaks.iter().map(|p| hex_to_bytes(p)).collect();
    let decoded = match decoded {
        Some(d) => d,
        None => return false,
    };
    let mut acc = decoded[decoded.len() - 1].clone();
    for peak in decoded[..decoded.len() - 1].iter().rev() {
        let mut h = Sha256::new();
        h.update([NODE_PREFIX]);
        h.update(mmr_size.to_be_bytes());
        h.update(peak);
        h.update(&acc);
        acc = h.finalize().to_vec();
    }
    bytes_to_hex(&acc) == expected_root_hex
}

fn hex_to_bytes(s: &str) -> Option<Vec<u8>> {
    if s.len() % 2 != 0 {
        return None;
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).ok())
        .collect()
}

fn bytes_to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

// ------------------------------------------------------------------ python
#[cfg(feature = "python")]
mod python {
    use super::*;
    use pyo3::exceptions::{PyTypeError, PyValueError};
    use pyo3::prelude::*;
    use pyo3::types::PyBytes;

    #[pyfunction]
    #[pyo3(name = "canonicalize")]
    fn py_canonicalize(py: Python<'_>, json_text: &str) -> PyResult<Py<PyBytes>> {
    let bytes = canonicalize(json_text).map_err(PyValueError::new_err)?;
    Ok(PyBytes::new_bound(py, &bytes).unbind())
    }

    #[pyfunction]
    #[pyo3(name = "sha256_hex")]
    fn py_sha256_hex(data: &[u8]) -> String {
    sha256_hex(data)
    }

    #[pyfunction]
    #[pyo3(name = "pae")]
    fn py_pae(py: Python<'_>, payload_type: &str, payload: &[u8]) -> Py<PyBytes> {
    PyBytes::new_bound(py, &pae(payload_type, payload)).unbind()
    }

    #[pyfunction]
    #[pyo3(name = "record_hash")]
    fn py_record_hash(json_text: &str) -> PyResult<String> {
    let bytes = canonicalize(json_text).map_err(PyValueError::new_err)?;
    Ok(sha256_hex(&bytes))
    }

    #[pyfunction]
    #[pyo3(name = "sign")]
    fn py_sign(py: Python<'_>, seed: &[u8], message: &[u8]) -> PyResult<Py<PyBytes>> {
    let seed: [u8; 32] = seed
        .try_into()
        .map_err(|_| PyTypeError::new_err("Ed25519 seed must be exactly 32 bytes"))?;
    let key = SigningKey::from_bytes(&seed);
    Ok(PyBytes::new_bound(py, &key.sign(message).to_bytes()).unbind())
    }

    #[pyfunction]
    #[pyo3(name = "public_from_seed")]
    fn py_public_from_seed(py: Python<'_>, seed: &[u8]) -> PyResult<Py<PyBytes>> {
    let seed: [u8; 32] = seed
        .try_into()
        .map_err(|_| PyTypeError::new_err("Ed25519 seed must be exactly 32 bytes"))?;
    let key = SigningKey::from_bytes(&seed);
    Ok(PyBytes::new_bound(py, key.verifying_key().as_bytes()).unbind())
    }

    /// Verify a raw Ed25519 signature. Never raises: a bad signature is an answer.
    #[pyfunction]
    #[pyo3(name = "verify")]
    fn py_verify(public: &[u8], signature: &[u8], message: &[u8]) -> bool {
    let pk: [u8; 32] = match public.try_into() {
        Ok(p) => p,
        Err(_) => return false,
    };
    let sig: [u8; 64] = match signature.try_into() {
        Ok(s) => s,
        Err(_) => return false,
    };
    match VerifyingKey::from_bytes(&pk) {
        Ok(k) => k.verify(message, &Signature::from_bytes(&sig)).is_ok(),
        Err(_) => false,
    }
    }

    #[pyfunction]
    #[pyo3(name = "hash_leaf")]
    fn py_hash_leaf(py: Python<'_>, payload: &[u8]) -> Py<PyBytes> {
    PyBytes::new_bound(py, &hash_leaf(payload)).unbind()
    }

    #[pyfunction]
    #[pyo3(name = "verify_inclusion")]
    fn py_verify_inclusion(payload: &[u8], leaf_index: u64, leaf_pos: u64,
                       path: Vec<String>, peaks: Vec<String>) -> bool {
    verify_inclusion(payload, leaf_index, leaf_pos, &path, &peaks)
    }

    #[pyfunction]
    #[pyo3(name = "verify_root")]
    fn py_verify_root(peaks: Vec<String>, mmr_size: u64, expected_root_hex: &str) -> bool {
    verify_root(&peaks, mmr_size, expected_root_hex)
    }

    #[pyfunction]
    #[pyo3(name = "b64encode")]
    fn py_b64encode(data: &[u8]) -> String {
    B64.encode(data)
    }

    #[pymodule]
    fn mira_agent_core_rs(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add("PAYLOAD_TYPE", PAYLOAD_TYPE)?;
    m.add_function(wrap_pyfunction!(py_canonicalize, m)?)?;
    m.add_function(wrap_pyfunction!(py_sha256_hex, m)?)?;
    m.add_function(wrap_pyfunction!(py_pae, m)?)?;
    m.add_function(wrap_pyfunction!(py_record_hash, m)?)?;
    m.add_function(wrap_pyfunction!(py_sign, m)?)?;
    m.add_function(wrap_pyfunction!(py_public_from_seed, m)?)?;
    m.add_function(wrap_pyfunction!(py_verify, m)?)?;
    m.add_function(wrap_pyfunction!(py_hash_leaf, m)?)?;
    m.add_function(wrap_pyfunction!(py_verify_inclusion, m)?)?;
    m.add_function(wrap_pyfunction!(py_verify_root, m)?)?;
    m.add_function(wrap_pyfunction!(py_b64encode, m)?)?;
    Ok(())
    }

    }

// ------------------------------------------------------------------- tests

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn jcs_sorts_keys_and_strips_whitespace() {
        let out = canonicalize(r#"{ "b": 1, "a": [1, 2, {"z": null}] }"#).unwrap();
        assert_eq!(String::from_utf8(out).unwrap(), r#"{"a":[1,2,{"z":null}],"b":1}"#);
    }

    #[test]
    fn integers_past_2_53_are_carried_as_strings() {
        // JCS serialises numbers per ECMAScript, so these cannot survive a
        // round trip through a double. Python does the same coercion; the
        // conformance vectors pin that the two agree.
        let out = canonicalize(r#"{"n": 9007199254740993}"#).unwrap();
        assert_eq!(String::from_utf8(out).unwrap(), r#"{"n":"9007199254740993"}"#);

        // and one below the boundary stays a number
        let out = canonicalize(r#"{"n": 9007199254740991}"#).unwrap();
        assert_eq!(String::from_utf8(out).unwrap(), r#"{"n":9007199254740991}"#);
    }

    #[test]
    fn pae_matches_the_dsse_shape() {
        let got = pae("t", b"ab");
        assert_eq!(got, b"DSSEv1 1 t 2 ab".to_vec());
    }

    #[test]
    fn leaf_and_node_hashing_are_domain_separated() {
        // a leaf must never be forgeable as an interior node
        assert_ne!(hash_leaf(b"x").to_vec(), hash_pos_pair(1, b"x", b"").to_vec());
    }

    #[test]
    fn leaf_positions_match_the_mmr_layout() {
        assert_eq!(leaf_index_to_pos(0), 0);
        assert_eq!(leaf_index_to_pos(1), 1);
        assert_eq!(leaf_index_to_pos(2), 3);
        assert_eq!(leaf_index_to_pos(3), 4);
        assert_eq!(leaf_index_to_pos(4), 7);
    }
}
